"""Add tmdb_id to Movie model

Revision ID: 447456b284fa
Revises: 
Create Date: 2024-10-16 17:40:36.709532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '447456b284fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crew')
    op.drop_table('cast')
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tmdb_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('release_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('overview', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('poster_path', sa.String(length=256), nullable=True))
        batch_op.create_unique_constraint(None, ['tmdb_id'])
        batch_op.drop_column('description')
        batch_op.drop_column('year')
        batch_op.drop_column('poster_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster_url', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('poster_path')
        batch_op.drop_column('overview')
        batch_op.drop_column('release_date')
        batch_op.drop_column('tmdb_id')

    op.create_table('cast',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], name='cast_movie_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='cast_pkey')
    )
    op.create_table('crew',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], name='crew_movie_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='crew_pkey')
    )
    # ### end Alembic commands ###
